import Head from 'next/head'
import { Inter } from '@next/font/google'

import { useState, useEffect, useRef, useCallback } from 'react'
import useSWR from 'swr'

import SearchForm from 'components/SearchForm'
import Flights from 'components/Flights'
import Header from 'components/Header'

import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [isDisabled, setIsDisabled] = useState(false)

  const [page, setPage] = useState(1)

  const API_FLIGHTS_PAGE = process.env.NEXT_PUBLIC_API_ENDPOINT + `?page=${page}`

  const [searchTerm, setSearchTerm] = useState('')

  const [flightNo, setFlightNo] = useState('')

  const API_FLIGHT_SEARCH = process.env.NEXT_PUBLIC_API_ENDPOINT + `/search/${flightNo}/`

  const fetcher = (...args) => fetch(...args).then((res) => res.json())

  const { data, isLoading, error } = useSWR(API_FLIGHTS_PAGE, fetcher)

  const [flightsData, setFlightsData] = useState({flights: [], page: 1, pageCount: 0, lastPage: false, exists: false})



  const handleInputChange = (event) => {
    setSearchTerm(event.target.value)
  }

  const handleSearchSubmit = (event, ref) => {
    if (ref && searchTerm) {
      setFlightNo(ref.current.toUpperCase())
    }
    setSearchTerm('')
    ref.current = ''
    setIsDisabled(true)
    event.preventDefault()
  }
  const handleRefillFlights = () => {
    setFlightsData(data)
    setFlightNo('')
    setIsDisabled(false)
  }

  useEffect(() => {
    if (data && !isLoading) {
      data.exists = true
      setFlightsData({...data, flights: flightsData.flights.concat(data.flights)})
    }
  }, [data])

  const handleSearch = useCallback(async () => {
    if (!flightNo) return

    try {
      const flightFound = await fetcher(API_FLIGHT_SEARCH)
      if (flightFound) {
        setFlightsData({
          ...flightsData,
          ...flightFound
        })
      }
    } catch {
      console.log('handleSearch failed')
    }
  }, [flightNo])

  useEffect(() => {
    handleSearch()
  }, [handleSearch])
  
  if (isLoading || !flightsData) return <div>Loading data...</div>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SearchForm 
          searchTerm={searchTerm}
          handleInputChange={handleInputChange}
          handleSearchSubmit={handleSearchSubmit}
          handleRefillFlights={handleRefillFlights}
        />
        <Flights 
          flightsData={flightsData} 
          error={error}
        />
        <button hidden={isDisabled} onClick={() => setPage(page + 1)}>Load more</button>
      </main>
    </>
  )
}
