import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Flights from 'components/Flights'
import { useState, useEffect } from 'react'
import useSWR from 'swr'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT

  const fetcher = (...args) => fetch(...args).then((res) => res.json())
  
  const [flightsData, setFlightsData] = useState([])

  const { data, error } = useSWR(API_ENDPOINT, fetcher)

  useEffect(() => {
    setFlightsData(data)
  }, [data])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Flights flightsData={flightsData} error={error}/>
      </main>
    </>
  )
}
